version: '3.8'

services:
  coffy-db:
    image: postgres:15-alpine
    container_name: coffy_flow_db
    environment:
      POSTGRES_USER: coffy_admin
      POSTGRES_PASSWORD: coffy_password
      POSTGRES_DB: coffy_flow_db
    ports:
      - "5432:5432"
    volumes:
      - coffy_pg_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  coffy_pg_data:
    name: coffy_flow_pg_data
